# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-05-30T09:38:49+00:00

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, Field


class Season(StrEnum):
    spring = "spring"
    summer = "summer"
    autumn = "autumn"
    winter = "winter"


class Weather(StrEnum):
    sunny = "sunny"
    cloudy = "cloudy"
    rainy = "rainy"
    any = "any"


class CostIndicator(StrEnum):
    free = "free"
    low_cost = "low_cost"
    paid = "paid"


class CompletionStatus(StrEnum):
    processing = "processing"
    ready = "ready"
    self_reported = "self_reported"


class ErrorResponse(BaseModel):
    detail: str
    code: str


class HealthResponse(BaseModel):
    status: Annotated[str, Field(examples=["ok"])]


class InviteResponse(BaseModel):
    invite_url: AnyUrl
    expires_at: AwareDatetime


class JoinByTokenRequest(BaseModel):
    token: UUID


class GoogleCallbackRequest(BaseModel):
    id_token: Annotated[str | None, Field(description="Google ID token (web flow)")] = None
    code: Annotated[str | None, Field(description="Authorization code (native flow)")] = None
    redirect_uri: Annotated[
        str | None,
        Field(description="Redirect URI used in the authorization request (native flow)"),
    ] = None
    code_verifier: Annotated[str | None, Field(description="PKCE code verifier (native flow, optional)")] = None


class RefreshRequest(BaseModel):
    refresh_token: str


class User(BaseModel):
    id: UUID
    email: EmailStr
    display_name: str
    profile_photo_url: AnyUrl | None = None
    points_balance: Annotated[int, Field(ge=0)]
    deletion_pending_at: AwareDatetime | None = None
    created_at: AwareDatetime


class UpdateUserRequest(BaseModel):
    display_name: Annotated[str | None, Field(min_length=1)] = None


class DeletionPendingResponse(BaseModel):
    message: str
    deletion_date: AwareDatetime


class GroupMembership(BaseModel):
    group_id: UUID | None = None
    group_name: str | None = None
    joined_at: AwareDatetime | None = None


class CreateConsentRequest(BaseModel):
    policy_version: Annotated[str, Field(examples=["1.0"])]
    data_storage_consent: Annotated[bool, Field(description="Required to use the app")]
    photo_processing_consent: Annotated[bool, Field(description="Required for photo-based completions")]
    location_consent: Annotated[
        bool | None,
        Field(description="Optional; enables weather-based activity suggestions"),
    ] = False


class ConsentRecord(BaseModel):
    id: UUID
    user_id: UUID
    policy_version: str
    consented_at: AwareDatetime
    data_storage_consent: bool
    photo_processing_consent: bool
    location_consent: bool


class FamilyMember(BaseModel):
    user_id: UUID
    display_name: str
    profile_photo_url: AnyUrl | None = None
    joined_at: AwareDatetime


class Family(BaseModel):
    id: UUID
    name: str | None = None
    members: list[FamilyMember]
    created_at: AwareDatetime


class CreateFamilyRequest(BaseModel):
    name: str | None = None


class FamilyCreatedResponse(BaseModel):
    family: Family
    membership: FamilyMember


class ChildProfile(BaseModel):
    id: UUID
    family_id: UUID
    nickname: str
    date_of_birth: Annotated[
        date,
        Field(description="Age is derived from this at query time; never stored as a computed field"),
    ]
    interests: Annotated[list[str], Field(description="Free-text tags; do not enter medical conditions")]
    created_at: AwareDatetime
    updated_at: AwareDatetime


class CreateChildRequest(BaseModel):
    nickname: Annotated[str, Field(min_length=1)]
    date_of_birth: date
    interests: list[str] | None = []


class UpdateChildRequest(BaseModel):
    nickname: Annotated[str | None, Field(min_length=1)] = None
    date_of_birth: date | None = None
    interests: list[str] | None = None


class FamilyParentInGroup(BaseModel):
    user_id: UUID
    display_name: str
    is_group_admin: bool


class GroupMemberFamily(BaseModel):
    family_id: UUID
    family_name: str | None = None
    joined_at: AwareDatetime
    parents: Annotated[
        list[FamilyParentInGroup],
        Field(description="Parents in this family and their group admin status"),
    ]


class GroupSummary(BaseModel):
    id: UUID
    name: str
    description: str | None = None
    is_admin: Annotated[
        bool,
        Field(description="Whether the authenticated user holds admin rights in this group"),
    ]
    created_at: AwareDatetime


class Group(GroupSummary):
    members: list[GroupMemberFamily]


class CreateGroupRequest(BaseModel):
    name: Annotated[str, Field(min_length=1)]
    description: str | None = None


class GroupAdminEntry(BaseModel):
    group_id: UUID
    user_id: UUID
    granted_at: AwareDatetime


class GrantAdminRequest(BaseModel):
    user_id: UUID


class FeedEntry(BaseModel):
    id: UUID
    family_id: UUID
    family_name: str | None = None
    activity_title: str
    photo_url: Annotated[
        AnyUrl | None,
        Field(description="Pre-signed URL; only present when status is ready"),
    ] = None
    caption: str | None = None
    completed_at: AwareDatetime


class Activity(BaseModel):
    id: UUID
    title: str
    description: str
    estimated_duration_minutes: Annotated[int, Field(ge=1)]
    age_min: Annotated[int, Field(ge=0)]
    age_max: Annotated[int, Field(ge=0)]
    cost_indicator: CostIndicator
    season_relevance: Annotated[list[Season] | None, Field(description="Null means year-round")] = None
    weather_suitability: list[Weather] | None = None
    is_partner_content: bool


class DisplayMode(StrEnum):
    collage = "collage"


class Status(StrEnum):
    upcoming = "upcoming"
    active = "active"
    completed = "completed"


class ChallengeSummary(BaseModel):
    id: UUID
    title: str
    description: str | None = None
    group_id: UUID | None = None
    start_date: date
    end_date: date
    display_mode: DisplayMode
    status: Status
    created_at: AwareDatetime


class CreateChallengeRequest(BaseModel):
    title: Annotated[str, Field(min_length=1)]
    description: str | None = None
    group_id: Annotated[UUID | None, Field(description="Null creates a personal/family challenge")] = None
    activity_ids: Annotated[
        list[UUID],
        Field(
            description="Activities in order — grid_position is assigned by their position in this list",
            min_length=1,
        ),
    ]
    start_date: date
    end_date: date


class PhotoUploadRequest(BaseModel):
    challenge_activity_id: UUID
    image: Annotated[bytes, Field(description="JPEG or PNG; maximum 10 MB")]
    caption: str | None = None
    shared_to_feed: bool | None = False


class PhotoUploadResponse(BaseModel):
    completion_id: UUID


class PhotoUrlResponse(BaseModel):
    url: AnyUrl
    expires_at: AwareDatetime


class Completion(BaseModel):
    id: UUID
    challenge_activity_id: UUID
    family_id: UUID
    completed_by_user_id: Annotated[
        UUID,
        Field(description="The parent who uploaded the photo or marked it complete"),
    ]
    status: CompletionStatus
    photo_url: Annotated[
        AnyUrl | None,
        Field(description="Pre-signed S3 URL; only present when status is ready"),
    ] = None
    caption: str | None = None
    shared_to_feed: bool
    completed_at: AwareDatetime
    updated_at: AwareDatetime


class CreateCompletionRequest(BaseModel):
    challenge_activity_id: UUID
    caption: str | None = None
    shared_to_feed: bool | None = False


class CompletionHistoryItem(BaseModel):
    id: UUID
    activity_title: str
    challenge_title: str
    status: CompletionStatus
    photo_url: AnyUrl | None = None
    caption: str | None = None
    completed_at: AwareDatetime


class TokenResponse(BaseModel):
    access_token: str
    refresh_token: str
    token_type: Annotated[str, Field(examples=["bearer"])]
    user: User


class DataExport(BaseModel):
    user: User
    children: list[ChildProfile]
    consents: list[ConsentRecord]
    group_memberships: list[GroupMembership]
    completions: list[CompletionHistoryItem]


class ChallengeActivitySlot(BaseModel):
    id: UUID
    activity_id: UUID
    activity: Activity
    grid_position: Annotated[
        int,
        Field(
            description="Visual position in the collage grid; not a completion order",
            ge=0,
        ),
    ]
    completion: Annotated[
        Completion | None,
        Field(description="The family's completion for this slot, if any"),
    ] = None
    families_completed_count: Annotated[
        int | None,
        Field(description="How many families in the group have completed this slot (group view only)"),
    ] = None


class Challenge(ChallengeSummary):
    activities: list[ChallengeActivitySlot]


class ChallengeWithProgress(Challenge):
    group_families_count: Annotated[
        int | None,
        Field(
            description="Total families in the group (for computing aggregate percentages); null for personal challenges"
        ),
    ] = None
