# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-05T12:13:20+00:00

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, Field


class Season(StrEnum):
    spring = "spring"
    summer = "summer"
    autumn = "autumn"
    winter = "winter"


class Weather(StrEnum):
    sunny = "sunny"
    cloudy = "cloudy"
    rainy = "rainy"
    any = "any"


class CostIndicator(StrEnum):
    free = "free"
    low_cost = "low_cost"
    paid = "paid"


class CompletionStatus(StrEnum):
    processing = "processing"
    pending_verification = "pending_verification"
    verified = "verified"
    rejected = "rejected"
    self_reported = "self_reported"


class EffortTier(StrEnum):
    casual = "casual"
    dedicated = "dedicated"


class Mood(StrEnum):
    bad = "bad"
    not_good = "not_good"
    okay = "okay"
    good = "good"
    super = "super"


class ErrorResponse(BaseModel):
    detail: str
    code: str


class HealthResponse(BaseModel):
    status: Annotated[str, Field(examples=["ok"])]


class InviteResponse(BaseModel):
    invite_url: AnyUrl
    expires_at: AwareDatetime


class JoinByTokenRequest(BaseModel):
    token: UUID


class GoogleCallbackRequest(BaseModel):
    id_token: Annotated[str | None, Field(description="Google ID token (web flow)")] = None
    code: Annotated[str | None, Field(description="Authorization code (native flow)")] = None
    redirect_uri: Annotated[
        str | None,
        Field(description="Redirect URI used in the authorization request (native flow)"),
    ] = None
    code_verifier: Annotated[str | None, Field(description="PKCE code verifier (native flow, optional)")] = None


class RefreshRequest(BaseModel):
    refresh_token: str


class User(BaseModel):
    id: UUID
    email: EmailStr
    display_name: str
    profile_photo_url: AnyUrl | None = None
    points_balance: Annotated[int, Field(ge=0)]
    preferred_language: Annotated[
        str,
        Field(
            description='BCP 47 language tag for content created by this user (e.g. "de")',
            min_length=2,
        ),
    ]
    deletion_pending_at: AwareDatetime | None = None
    created_at: AwareDatetime


class UpdateUserRequest(BaseModel):
    display_name: Annotated[str | None, Field(min_length=1)] = None
    image: bytes | None = None


class DeletionPendingResponse(BaseModel):
    message: str
    deletion_date: AwareDatetime


class GroupMembership(BaseModel):
    group_id: UUID | None = None
    group_name: str | None = None
    joined_at: AwareDatetime | None = None


class CreateConsentRequest(BaseModel):
    policy_version: Annotated[str, Field(examples=["1.0"])]
    data_storage_consent: Annotated[bool, Field(description="Required to use the app")]
    photo_processing_consent: Annotated[bool, Field(description="Required for photo-based completions")]
    location_consent: Annotated[
        bool | None,
        Field(description="Optional; enables weather-based activity suggestions"),
    ] = False


class ConsentRecord(BaseModel):
    id: UUID
    user_id: UUID
    policy_version: str
    consented_at: AwareDatetime
    data_storage_consent: bool
    photo_processing_consent: bool
    location_consent: bool


class FamilyMember(BaseModel):
    user_id: UUID
    display_name: str
    profile_photo_url: AnyUrl | None = None
    joined_at: AwareDatetime


class Family(BaseModel):
    id: UUID
    name: str | None = None
    members: list[FamilyMember]
    created_at: AwareDatetime


class CreateFamilyRequest(BaseModel):
    name: str | None = None


class FamilyCreatedResponse(BaseModel):
    family: Family
    membership: FamilyMember


class ChildProfile(BaseModel):
    id: UUID
    family_id: UUID
    nickname: str
    date_of_birth: Annotated[
        date,
        Field(description="Age is derived from this at query time; never stored as a computed field"),
    ]
    interests: Annotated[list[str], Field(description="Free-text tags; do not enter medical conditions")]
    created_at: AwareDatetime
    updated_at: AwareDatetime


class CreateChildRequest(BaseModel):
    nickname: Annotated[str, Field(min_length=1)]
    date_of_birth: date
    interests: list[str] | None = []


class UpdateChildRequest(BaseModel):
    nickname: Annotated[str | None, Field(min_length=1)] = None
    date_of_birth: date | None = None
    interests: list[str] | None = None


class FamilyParentInGroup(BaseModel):
    user_id: UUID
    display_name: str
    is_group_admin: bool


class GroupMemberFamily(BaseModel):
    family_id: UUID
    family_name: str | None = None
    joined_at: AwareDatetime
    parents: Annotated[
        list[FamilyParentInGroup],
        Field(description="Parents in this family and their group admin status"),
    ]


class GroupSummary(BaseModel):
    id: UUID
    name: str
    description: str | None = None
    is_admin: Annotated[
        bool,
        Field(description="Whether the authenticated user holds admin rights in this group"),
    ]
    created_at: AwareDatetime


class Group(GroupSummary):
    members: list[GroupMemberFamily]


class CreateGroupRequest(BaseModel):
    name: Annotated[str, Field(min_length=1)]
    description: str | None = None


class GroupAdminEntry(BaseModel):
    group_id: UUID
    user_id: UUID
    granted_at: AwareDatetime


class GrantAdminRequest(BaseModel):
    user_id: UUID


class FeedEntry(BaseModel):
    id: UUID
    family_id: UUID
    family_name: str | None = None
    activity_title: str
    photo_url: Annotated[
        AnyUrl | None,
        Field(description="Pre-signed URL; only present when status is ready"),
    ] = None
    caption: str | None = None
    completed_at: AwareDatetime


class Activity(BaseModel):
    id: UUID
    title: str
    description: str
    estimated_duration_minutes: Annotated[int, Field(ge=1)]
    age_min: Annotated[int, Field(ge=0)]
    age_max: Annotated[int, Field(ge=0)]
    cost_indicator: CostIndicator
    season_relevance: Annotated[list[Season] | None, Field(description="Null means year-round")] = None
    weather_suitability: list[Weather] | None = None
    is_partner_content: bool
    effort_tier: EffortTier
    language: Annotated[
        str,
        Field(
            description='BCP 47 language tag for the activity\'s content language (e.g. "de")',
            min_length=2,
        ),
    ]


class CostIndicator1(StrEnum):
    free = "free"
    low_cost = "low_cost"


class CreateActivityRequest(BaseModel):
    title: Annotated[str, Field(max_length=100)]
    description: Annotated[str | None, Field(max_length=500)] = None
    estimated_duration_minutes: Annotated[int | None, Field(ge=1)] = 30
    cost_indicator: Annotated[CostIndicator1 | None, Field(description='Defaults to "free" when omitted.')] = None


class CollagePreset(BaseModel):
    id: UUID
    name: str
    description: str
    activity_ids: Annotated[
        list[UUID],
        Field(description="Exactly nine activity ids, ordered by grid position 0–8"),
    ]


class DisplayMode(StrEnum):
    collage = "collage"


class Status(StrEnum):
    active = "active"
    completed = "completed"


class ChallengeSummary(BaseModel):
    id: UUID
    title: str
    description: str | None = None
    group_id: UUID | None = None
    is_private: Annotated[
        bool,
        Field(description="When true, photos uploaded to this challenge default to NOT being shared to group feeds"),
    ]
    is_featured: Annotated[
        bool | None,
        Field(description="Featured challenges grant +5 bonus points per verified completion"),
    ] = False
    display_mode: DisplayMode
    status: Annotated[
        Status,
        Field(description="Challenges have no dates — a challenge is active until every slot is filled"),
    ]
    created_at: AwareDatetime


class CreateChallengeRequest(BaseModel):
    title: Annotated[str, Field(min_length=1)]
    description: str | None = None
    group_id: Annotated[UUID | None, Field(description="Null creates a personal/family challenge")] = None
    activity_ids: Annotated[
        list[UUID],
        Field(
            description="Activities in order — grid_position is assigned by their position in this list",
            min_length=1,
        ),
    ]
    is_private: Annotated[
        bool | None,
        Field(description="When false, uploads default to being shared to the feeds of shared_group_ids"),
    ] = True
    shared_group_ids: Annotated[
        list[UUID] | None,
        Field(description="Groups (the caller's family must be a member) whose feeds receive opted-in photos"),
    ] = []


class UpdateChallengeRequest(BaseModel):
    is_private: Annotated[
        bool | None,
        Field(description="When true, uploads default to not being shared to group feeds"),
    ] = None


class ChallengeParticipant(BaseModel):
    user_id: UUID
    display_name: str
    family_id: UUID
    invited_by_user_id: UUID
    created_at: AwareDatetime


class InviteParticipantRequest(BaseModel):
    user_id: UUID


class Friend(BaseModel):
    user_id: UUID
    display_name: str
    shared_group_names: Annotated[
        list[str],
        Field(description="Names of the groups the caller shares with this parent"),
    ]


class Type(StrEnum):
    challenge_invite = "challenge_invite"


class NotificationItem(BaseModel):
    id: UUID
    type: Type
    actor_user_id: UUID | None = None
    actor_display_name: str | None = None
    challenge_id: UUID | None = None
    challenge_title: str | None = None
    created_at: AwareDatetime
    read: bool


class PhotoUploadRequest(BaseModel):
    challenge_activity_id: UUID
    image: Annotated[bytes, Field(description="JPEG or PNG; maximum 10 MB")]
    caption: str | None = None
    shared_to_feed: bool | None = False
    duration_minutes: Annotated[
        int | None,
        Field(
            description="Minutes the family reports spending on the activity, from a fixed dropdown. Required when the activity's resolved point tier is casual (server-enforced); optional otherwise.\n"
        ),
    ] = None


class PhotoUploadResponse(BaseModel):
    completion_id: UUID


class PhotoUrlResponse(BaseModel):
    url: AnyUrl
    expires_at: AwareDatetime


class Completion(BaseModel):
    id: UUID
    challenge_activity_id: UUID
    family_id: UUID
    completed_by_user_id: Annotated[
        UUID,
        Field(description="The parent who uploaded the photo or marked it complete"),
    ]
    status: CompletionStatus
    photo_url: Annotated[
        AnyUrl | None,
        Field(description="Pre-signed S3 URL; present when status is pending_verification, verified, or rejected"),
    ] = None
    caption: str | None = None
    rejection_reason: Annotated[str | None, Field(description="Set when status is rejected; null otherwise")] = None
    duration_minutes: Annotated[
        int | None,
        Field(description="Minutes the family reported spending on the activity"),
    ] = None
    shared_to_feed: bool
    completed_at: AwareDatetime
    updated_at: AwareDatetime


class CreateCompletionRequest(BaseModel):
    challenge_activity_id: UUID
    caption: str | None = None
    shared_to_feed: bool | None = False


class CompletionHistoryItem(BaseModel):
    id: UUID
    activity_title: str
    challenge_title: str
    status: CompletionStatus
    photo_url: AnyUrl | None = None
    caption: str | None = None
    rejection_reason: Annotated[str | None, Field(description="Set when status is rejected; null otherwise")] = None
    duration_minutes: int | None = None
    completed_at: AwareDatetime


class PhotoReuploadRequest(BaseModel):
    image: Annotated[bytes, Field(description="JPEG or PNG; maximum 10 MB")]


class ReuploadResponse(BaseModel):
    completion_id: UUID
    status: CompletionStatus


class PendingVerificationItem(BaseModel):
    completion_id: UUID
    family_name: Annotated[
        str,
        Field(description="Family display name only — no child names or child-identifiable data"),
    ]
    activity_title: str
    photo_url: Annotated[AnyUrl | None, Field(description="Pre-signed S3 URL for the submitted photo")] = None
    duration_minutes: int | None = None
    submitted_at: AwareDatetime


class VerificationQueue(BaseModel):
    items: list[PendingVerificationItem]
    total: int


class RejectPayload(BaseModel):
    reason: Annotated[
        str | None,
        Field(description="Optional. When given, it is shown to the family alongside the rejected photo."),
    ] = None


class VerificationActionResponse(BaseModel):
    completion_id: UUID
    status: CompletionStatus
    points_awarded: Annotated[
        int | None,
        Field(description="Total points credited on approval (base + bonus); null on reject"),
    ] = None


class RewardLevelState(StrEnum):
    locked = "locked"
    unlocked = "unlocked"
    redeemed_this_quarter = "redeemed_this_quarter"


class RewardLevelProgress(BaseModel):
    id: UUID
    level_number: int
    points_threshold: int
    title: Annotated[
        str,
        Field(description="Localised via Accept-Language (German base, English fallback)"),
    ]
    description: str | None = None
    choice_options: Annotated[
        list[str] | None,
        Field(description="Present when redemption requires choosing one option"),
    ] = None
    annual_redemption_cap: int | None = None
    state: RewardLevelState
    redemptions_this_year: Annotated[
        int | None,
        Field(description="Only set for levels with an annual redemption cap"),
    ] = None


class RewardsBalance(BaseModel):
    quarter_key: Annotated[str, Field(examples=["2026-Q3"])]
    balance: Annotated[
        int,
        Field(description="Sum of ledger points awarded in the current calendar quarter (UTC)"),
    ]
    levels: list[RewardLevelProgress]


class RedeemPayload(BaseModel):
    chosen_option: Annotated[str | None, Field(description="Required when the level has choice_options")] = None


class RedemptionResult(BaseModel):
    redemption_id: UUID
    reward_level_id: UUID
    chosen_option: str | None = None
    voucher_code: Annotated[str, Field(examples=["BOND-7K2P9Q"])]
    redeemed_at: AwareDatetime


class WeekStats(BaseModel):
    activities: Annotated[int, Field(examples=[1], ge=0)]
    photos: Annotated[int, Field(examples=[1], ge=0)]


class StreakStats(BaseModel):
    current_days: Annotated[
        int,
        Field(
            description="Consecutive days with at least one completion",
            examples=[4],
            ge=0,
        ),
    ]
    last_days: Annotated[
        int | None,
        Field(
            description="Length of the previous streak before it was reset",
            examples=[None],
        ),
    ] = None
    longest_days: Annotated[int, Field(examples=[6], ge=0)]
    frozen_today: Annotated[
        bool,
        Field(
            description="A one-day grace freeze is currently protecting the streak",
            examples=[False],
        ),
    ]


class AllTimeStats(BaseModel):
    activities: Annotated[int, Field(examples=[27], ge=0)]
    photos: Annotated[int, Field(examples=[24], ge=0)]
    challenges: Annotated[int, Field(examples=[5], ge=0)]


class FamilySettingsUpdate(BaseModel):
    weekly_goal: Annotated[int | None, Field(examples=[3], ge=1)] = None


class JournalEntry(BaseModel):
    id: UUID
    entry_date: Annotated[date, Field(description="The user's local calendar date the mood refers to")]
    mood: Mood
    created_at: AwareDatetime


class CreateJournalEntryRequest(BaseModel):
    entry_date: Annotated[
        date,
        Field(description='The user\'s local calendar date (clients send their own "today")'),
    ]
    mood: Mood


class TokenResponse(BaseModel):
    access_token: str
    refresh_token: str
    token_type: Annotated[str, Field(examples=["bearer"])]
    user: User


class DataExport(BaseModel):
    user: User
    children: list[ChildProfile]
    consents: list[ConsentRecord]
    group_memberships: list[GroupMembership]
    completions: list[CompletionHistoryItem]


class ChallengeActivitySlot(BaseModel):
    id: UUID
    activity_id: UUID
    activity: Activity
    grid_position: Annotated[
        int,
        Field(
            description="Visual position in the collage grid; not a completion order",
            ge=0,
        ),
    ]
    completion: Annotated[
        Completion | None,
        Field(description="The family's completion for this slot, if any"),
    ] = None
    families_completed_count: Annotated[
        int | None,
        Field(description="How many families in the group have completed this slot (group view only)"),
    ] = None


class Challenge(ChallengeSummary):
    activities: list[ChallengeActivitySlot]


class ChallengeWithProgress(Challenge):
    group_families_count: Annotated[
        int | None,
        Field(
            description="Total families in the group (for computing aggregate percentages); null for personal challenges"
        ),
    ] = None
    shared_group_ids: Annotated[
        list[UUID] | None,
        Field(description="Groups whose feeds receive this challenge's opted-in photos"),
    ] = []


class FamilyProgress(BaseModel):
    weekly_goal: Annotated[
        int,
        Field(description="Family's self-set weekly activity target", examples=[2], ge=1),
    ]
    this_week: WeekStats
    streak: StreakStats
    all_time: AllTimeStats
