# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-05-27T09:11:13+00:00

from __future__ import annotations

from typing import List, Optional, Union

from fastapi import FastAPI, Path, Query, UploadFile
from pydantic import conint, constr

from .models import (
    Challenge,
    ChallengeCreate,
    ChallengeProgress,
    ChallengeSummary,
    Classroom,
    ClassroomCreate,
    ClassroomsClassroomIdFamiliesPostRequest,
    ClassroomsClassroomIdFeedTogglePutRequest,
    Error,
    FamiliesFamilyIdChallengesChallengeIdActivitiesActivityIndexPostResponse,
    FamiliesFamilyIdMembersPostRequest,
    FamiliesFamilyIdStreakGetResponse,
    Family,
    FamilyCreate,
    FeaturedChallenge,
    FeedEntry,
    Photo,
    SearchResults,
    Status1,
    Type,
    User,
    UserCreate,
    UserUpdate,
)

app = FastAPI(
    title='DigitalBalanceAtHome',
    description='API for DigitalBalanceAtHome Project - encouraging screen-free family activities through photo bingo challenges.',
    version='0.0.1',
    contact={'name': 'Viktoria Kabaivanova', 'email': 'viktoria.kabaivanova@tum.de'},
    servers=[{'url': 'http://localhost:8000', 'description': 'during development'}],
)

#TODO: implement the endpoints after setting up the database

@app.get('/challenges', response_model=List[ChallengeSummary], tags=['Challenges'])
def get_challenges(
    page_limit: Optional[conint(ge=1, le=50)] = Query(20, alias='pageLimit')
) -> List[ChallengeSummary]:
    """
    List all available challenges
    """
    pass


@app.post(
    '/challenges',
    response_model=None,
    responses={'201': {'model': Challenge}, '400': {'model': Error}},
    tags=['Challenges'],
)
def create_challenge(body: ChallengeCreate) -> Optional[Union[Challenge, Error]]:
    """
    Create a new challenge (teacher/admin only)
    """
    pass


@app.get('/challenges/featured', response_model=FeaturedChallenge, tags=['Challenges'])
def get_featured_challenge() -> FeaturedChallenge:
    """
    Get the current "Game of the Week" featured challenge
    """
    pass


@app.get(
    '/challenges/{challengeId}',
    response_model=Challenge,
    responses={'404': {'model': Error}},
    tags=['Challenges'],
)
def get_challenge(
    challenge_id: int = Path(..., alias='challengeId')
) -> Union[Challenge, Error]:
    """
    Get a challenge with its 9 activities
    """
    pass


@app.put(
    '/challenges/{challengeId}',
    response_model=Challenge,
    responses={'404': {'model': Error}},
    tags=['Challenges'],
)
def update_challenge(
    challenge_id: int = Path(..., alias='challengeId'), body: ChallengeCreate = ...
) -> Union[Challenge, Error]:
    """
    Update a challenge
    """
    pass


@app.delete(
    '/challenges/{challengeId}',
    response_model=None,
    responses={'404': {'model': Error}},
    tags=['Challenges'],
)
def delete_challenge(
    challenge_id: int = Path(..., alias='challengeId')
) -> Optional[Error]:
    """
    Delete a challenge
    """
    pass


@app.get(
    '/challenges/{challengeId}/completions',
    response_model=List[FeedEntry],
    responses={'404': {'model': Error}},
    tags=['Feed'],
)
def get_challenge_completions(
    page_limit: Optional[conint(ge=1, le=50)] = Query(20, alias='pageLimit'),
    challenge_id: int = Path(..., alias='challengeId'),
) -> Union[List[FeedEntry], Error]:
    """
    Get recent completions across all families for a specific challenge
    """
    pass


@app.get(
    '/challenges/{challengeId}/related',
    response_model=List[ChallengeSummary],
    responses={'404': {'model': Error}},
    tags=['Challenges'],
)
def get_related_challenges(
    challenge_id: int = Path(..., alias='challengeId')
) -> Union[List[ChallengeSummary], Error]:
    """
    Get challenges related to the given one
    """
    pass


@app.get('/classrooms', response_model=List[Classroom], tags=['Classrooms'])
def get_classrooms(
    page_limit: Optional[conint(ge=1, le=50)] = Query(20, alias='pageLimit')
) -> List[Classroom]:
    """
    List all classrooms
    """
    pass


@app.post(
    '/classrooms',
    response_model=None,
    responses={'201': {'model': Classroom}, '400': {'model': Error}},
    tags=['Classrooms'],
)
def create_classroom(body: ClassroomCreate) -> Optional[Union[Classroom, Error]]:
    """
    Create a new classroom (teacher/admin only)
    """
    pass


@app.get(
    '/classrooms/{classroomId}',
    response_model=Classroom,
    responses={'404': {'model': Error}},
    tags=['Classrooms'],
)
def get_classroom(
    classroom_id: int = Path(..., alias='classroomId')
) -> Union[Classroom, Error]:
    """
    Get a classroom by ID
    """
    pass


@app.put(
    '/classrooms/{classroomId}',
    response_model=Classroom,
    responses={'404': {'model': Error}},
    tags=['Classrooms'],
)
def update_classroom(
    classroom_id: int = Path(..., alias='classroomId'), body: ClassroomCreate = ...
) -> Union[Classroom, Error]:
    """
    Update a classroom
    """
    pass


@app.delete(
    '/classrooms/{classroomId}',
    response_model=None,
    responses={'404': {'model': Error}},
    tags=['Classrooms'],
)
def delete_classroom(
    classroom_id: int = Path(..., alias='classroomId')
) -> Optional[Error]:
    """
    Delete a classroom
    """
    pass


@app.post(
    '/classrooms/{classroomId}/families',
    response_model=Classroom,
    responses={'404': {'model': Error}},
    tags=['Classrooms'],
)
def add_family_to_classroom(
    classroom_id: int = Path(..., alias='classroomId'),
    body: ClassroomsClassroomIdFamiliesPostRequest = ...,
) -> Union[Classroom, Error]:
    """
    Add a family to a classroom
    """
    pass


@app.delete(
    '/classrooms/{classroomId}/families/{familyId}',
    response_model=None,
    responses={'404': {'model': Error}},
    tags=['Classrooms'],
)
def remove_family_from_classroom(
    classroom_id: int = Path(..., alias='classroomId'),
    family_id: int = Path(..., alias='familyId'),
) -> Optional[Error]:
    """
    Remove a family from a classroom
    """
    pass


@app.get(
    '/classrooms/{classroomId}/feed',
    response_model=List[FeedEntry],
    responses={'404': {'model': Error}},
    tags=['Feed'],
)
def get_classroom_feed(
    page_limit: Optional[conint(ge=1, le=50)] = Query(20, alias='pageLimit'),
    classroom_id: int = Path(..., alias='classroomId'),
) -> Union[List[FeedEntry], Error]:
    """
    Get the activity feed for a classroom
    """
    pass


@app.put(
    '/classrooms/{classroomId}/feed-toggle',
    response_model=Classroom,
    responses={'404': {'model': Error}},
    tags=['Classrooms'],
)
def toggle_classroom_feed(
    classroom_id: int = Path(..., alias='classroomId'),
    body: ClassroomsClassroomIdFeedTogglePutRequest = ...,
) -> Union[Classroom, Error]:
    """
    Toggle the activity feed on or off for a classroom
    """
    pass


@app.get('/families', response_model=List[Family], tags=['Families'])
def get_families(
    page_limit: Optional[conint(ge=1, le=50)] = Query(20, alias='pageLimit')
) -> List[Family]:
    """
    List all families
    """
    pass


@app.post(
    '/families',
    response_model=None,
    responses={'201': {'model': Family}, '400': {'model': Error}},
    tags=['Families'],
)
def create_family(body: FamilyCreate) -> Optional[Union[Family, Error]]:
    """
    Create a new family
    """
    pass


@app.get(
    '/families/{familyId}',
    response_model=Family,
    responses={'404': {'model': Error}},
    tags=['Families'],
)
def get_family(family_id: int = Path(..., alias='familyId')) -> Union[Family, Error]:
    """
    Get a family by ID
    """
    pass


@app.put(
    '/families/{familyId}',
    response_model=Family,
    responses={'404': {'model': Error}},
    tags=['Families'],
)
def update_family(
    family_id: int = Path(..., alias='familyId'), body: FamilyCreate = ...
) -> Union[Family, Error]:
    """
    Update a family
    """
    pass


@app.delete(
    '/families/{familyId}',
    response_model=None,
    responses={'404': {'model': Error}},
    tags=['Families'],
)
def delete_family(family_id: int = Path(..., alias='familyId')) -> Optional[Error]:
    """
    Delete a family
    """
    pass


@app.get(
    '/families/{familyId}/challenges',
    response_model=List[ChallengeProgress],
    responses={'404': {'model': Error}},
    tags=['Challenge Progress'],
)
def get_family_challenges(
    status: Optional[Status1] = 'all', family_id: int = Path(..., alias='familyId')
) -> Union[List[ChallengeProgress], Error]:
    """
    Get all challenges a family has joined (ongoing and completed)
    """
    pass


@app.get(
    '/families/{familyId}/challenges/{challengeId}',
    response_model=ChallengeProgress,
    responses={'404': {'model': Error}},
    tags=['Challenge Progress'],
)
def get_family_challenge_progress(
    family_id: int = Path(..., alias='familyId'),
    challenge_id: int = Path(..., alias='challengeId'),
) -> Union[ChallengeProgress, Error]:
    """
    Get a family's progress on a specific challenge
    """
    pass


@app.post(
    '/families/{familyId}/challenges/{challengeId}/activities/{activityIndex}',
    response_model=FamiliesFamilyIdChallengesChallengeIdActivitiesActivityIndexPostResponse,
    responses={'400': {'model': Error}, '404': {'model': Error}},
    tags=['Challenge Progress'],
)
def complete_activity(
    family_id: int = Path(..., alias='familyId'),
    challenge_id: int = Path(..., alias='challengeId'),
    activity_index: conint(ge=0, le=8) = Path(..., alias='activityIndex'),
    photo: UploadFile = ...,
) -> Union[
    FamiliesFamilyIdChallengesChallengeIdActivitiesActivityIndexPostResponse, Error
]:
    """
    Complete a bingo cell by uploading a photo
    """
    pass


@app.get(
    '/families/{familyId}/challenges/{challengeId}/export',
    response_model=bytes,
    responses={'400': {'model': Error}, '404': {'model': Error}},
    tags=['Challenge Progress'],
)
def export_challenge(
    family_id: int = Path(..., alias='familyId'),
    challenge_id: int = Path(..., alias='challengeId'),
) -> Union[bytes, Error]:
    """
    Export a completed challenge as a photo collage
    """
    pass


@app.post(
    '/families/{familyId}/challenges/{challengeId}/join',
    response_model=None,
    responses={
        '201': {'model': ChallengeProgress},
        '409': {'model': Error},
        '404': {'model': Error},
    },
    tags=['Challenge Progress'],
)
def join_challenge(
    family_id: int = Path(..., alias='familyId'),
    challenge_id: int = Path(..., alias='challengeId'),
) -> Optional[Union[ChallengeProgress, Error]]:
    """
    Join a challenge as a family
    """
    pass


@app.post(
    '/families/{familyId}/members',
    response_model=Family,
    responses={'400': {'model': Error}, '404': {'model': Error}},
    tags=['Families'],
)
def add_family_member(
    family_id: int = Path(..., alias='familyId'),
    body: FamiliesFamilyIdMembersPostRequest = ...,
) -> Union[Family, Error]:
    """
    Add a member (parent or child) to a family
    """
    pass


@app.delete(
    '/families/{familyId}/members/{userId}',
    response_model=None,
    responses={'400': {'model': Error}, '404': {'model': Error}},
    tags=['Families'],
)
def remove_family_member(
    family_id: int = Path(..., alias='familyId'),
    user_id: int = Path(..., alias='userId'),
) -> Optional[Error]:
    """
    Remove a member from a family
    """
    pass


@app.get(
    '/families/{familyId}/photos',
    response_model=List[Photo],
    responses={'404': {'model': Error}},
    tags=['Photos'],
)
def get_family_photos(
    page_limit: Optional[conint(ge=1, le=50)] = Query(20, alias='pageLimit'),
    family_id: int = Path(..., alias='familyId'),
) -> Union[List[Photo], Error]:
    """
    Get all photos uploaded by a family
    """
    pass


@app.get(
    '/families/{familyId}/streak',
    response_model=FamiliesFamilyIdStreakGetResponse,
    responses={'404': {'model': Error}},
    tags=['Families'],
)
def get_family_streak(
    family_id: int = Path(..., alias='familyId')
) -> Union[FamiliesFamilyIdStreakGetResponse, Error]:
    """
    Get the current activity streak for a family
    """
    pass


@app.post(
    '/photos',
    response_model=None,
    responses={'201': {'model': Photo}, '400': {'model': Error}},
    tags=['Photos'],
)
def upload_photo(file: UploadFile) -> Optional[Union[Photo, Error]]:
    """
    Upload a photo
    """
    pass


@app.get(
    '/photos/{photoId}',
    response_model=Photo,
    responses={'404': {'model': Error}},
    tags=['Photos'],
)
def get_photo(photo_id: int = Path(..., alias='photoId')) -> Union[Photo, Error]:
    """
    Get photo metadata
    """
    pass


@app.delete(
    '/photos/{photoId}',
    response_model=None,
    responses={'404': {'model': Error}},
    tags=['Photos'],
)
def delete_photo(photo_id: int = Path(..., alias='photoId')) -> Optional[Error]:
    """
    Delete a photo
    """
    pass


@app.get(
    '/photos/{photoId}/image',
    response_model=bytes,
    responses={'404': {'model': Error}},
    tags=['Photos'],
)
def get_photo_image(photo_id: int = Path(..., alias='photoId')) -> Union[bytes, Error]:
    """
    Get the actual photo file
    """
    pass


@app.get('/search', response_model=SearchResults, tags=['Search'])
def search(q: constr(min_length=1), type: Optional[Type] = 'all') -> SearchResults:
    """
    Search across users, families, and challenges
    """
    pass


@app.get('/users', response_model=List[User], tags=['Users'])
def get_users(
    page_limit: Optional[conint(ge=1, le=50)] = Query(20, alias='pageLimit'),
    body_limit: Optional[conint(ge=10, le=20)] = Query(None, alias='bodyLimit'),
) -> List[User]:
    """
    List all users
    """
    pass


@app.post(
    '/users',
    response_model=None,
    responses={'201': {'model': User}, '400': {'model': Error}},
    tags=['Users'],
)
def create_user(body: UserCreate) -> Optional[Union[User, Error]]:
    """
    Create a new user
    """
    pass


@app.get(
    '/users/{userId}',
    response_model=User,
    responses={'404': {'model': Error}},
    tags=['Users'],
)
def get_user(user_id: int = Path(..., alias='userId')) -> Union[User, Error]:
    """
    Get a user by ID
    """
    pass


@app.put(
    '/users/{userId}',
    response_model=User,
    responses={'404': {'model': Error}},
    tags=['Users'],
)
def update_user(
    user_id: int = Path(..., alias='userId'), body: UserUpdate = ...
) -> Union[User, Error]:
    """
    Update a user
    """
    pass


@app.delete(
    '/users/{userId}',
    response_model=None,
    responses={'404': {'model': Error}},
    tags=['Users'],
)
def delete_user(user_id: int = Path(..., alias='userId')) -> Optional[Error]:
    """
    Delete a user
    """
    pass
