# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-05-26T08:17:01+00:00

from __future__ import annotations

from typing import List, Optional

from fastapi import FastAPI, Query
from pydantic import conint

from models import User, Users

app = FastAPI(
    title='DigitalBalanceAtHome',
    description='API for DigitalBalanceAtHome Project',
    version='0.0.1',
    contact={'name': 'Viktoria Kabaivanova', 'email': 'viktoria.kabaivanova@tum.de'},
    servers=[{'url': 'http://localhost:8000', 'description': 'during development'}],
)


@app.get('/users', response_model=List[Users])
def get_users(
    body_limit: Optional[conint(ge=10, le=20)] = Query(None, alias='bodyLimit'),
    page_limit: Optional[conint(ge=1, le=5)] = Query(None, alias='pageLimit'),
) -> List[Users]:
    pass


@app.post('/users', response_model=None)
def post_users(body: User) -> None:
    pass


@app.get('/users/{id}', response_model=User)
def get_users_id(id: int) -> User:
    pass
