# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-05-27T09:11:13+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, conint


class Error(BaseModel):
    message: str = Field(..., examples=['Resource not found'])


class UserRole(Enum):
    parent = 'parent'
    child = 'child'
    teacher_admin = 'teacher_admin'


class UserCreate(BaseModel):
    name: str = Field(..., examples=['Max Mustermann'])
    role: UserRole
    profilePicture: Optional[AnyUrl] = Field(
        None, description="URL to the user's profile picture"
    )


class UserUpdate(BaseModel):
    name: Optional[str] = None
    profilePicture: Optional[AnyUrl] = None


class User(BaseModel):
    id: int = Field(..., examples=[4])
    name: str = Field(..., examples=['Max Mustermann'])
    role: UserRole
    profilePicture: Optional[AnyUrl] = None


class FamilyCreate(BaseModel):
    parentIds: List[int] = Field(
        ..., description='User IDs of the parents (1 or 2)', max_length=2, min_length=1
    )
    childIds: List[int] = Field(
        ..., description='User IDs of the children (at least 1)', min_length=1
    )


class Family(BaseModel):
    id: int = Field(..., examples=[1])
    parents: List[User] = Field(..., max_length=2, min_length=1)
    children: List[User] = Field(..., min_length=1)
    displayName: Optional[str] = Field(
        None,
        description='Auto-generated display name, e.g. "Sarah & Emma"',
        examples=['Sarah & Emma'],
    )
    totalPoints: int = Field(..., examples=[340])
    photoCount: Optional[int] = Field(None, examples=[15])
    challengeCount: Optional[int] = Field(None, examples=[5])
    rank: Optional[int] = Field(None, examples=[4])
    level: Optional[int] = Field(None, examples=[12])


class ClassroomCreate(BaseModel):
    name: str = Field(..., examples=['Grade 3A'])
    teacherId: int = Field(
        ..., description='User ID of the teacher who manages this classroom'
    )


class Classroom(BaseModel):
    id: int = Field(..., examples=[1])
    name: str = Field(..., examples=['Grade 3A'])
    teacher: User
    feedEnabled: bool
    familyIds: Optional[List[int]] = Field(
        None, description='IDs of families in this classroom'
    )


class ChallengeCreate(BaseModel):
    title: str = Field(..., examples=['Cooking Challenge'])
    icon: str = Field(..., description='Emoji icon for the challenge', examples=['🍳'])
    description: Optional[str] = Field(None, examples=['Kitchen fun with the family'])
    activities: List[str] = Field(
        ...,
        description='Exactly 9 activity titles for the 3x3 bingo grid',
        max_length=9,
        min_length=9,
    )


class ChallengeSummary(BaseModel):
    id: int = Field(..., examples=[1])
    title: str = Field(..., examples=['Cooking Challenge'])
    icon: str = Field(..., examples=['🍳'])
    description: Optional[str] = Field(None, examples=['Kitchen fun with the family'])


class Challenge(ChallengeSummary):
    activities: List[str] = Field(
        ...,
        description='The 9 activity titles in bingo grid order',
        max_length=9,
        min_length=9,
    )


class FeaturedChallenge(Challenge):
    endsAt: AwareDatetime = Field(..., description='When the featured period ends')


class CompletedCell(BaseModel):
    activityIndex: conint(ge=0, le=8)
    photoId: int
    photoUrl: Optional[AnyUrl] = None
    completedAt: AwareDatetime


class Status(Enum):
    ongoing = 'ongoing'
    completed = 'completed'


class ChallengeProgress(BaseModel):
    familyId: int
    challengeId: int
    challenge: Optional[ChallengeSummary] = None
    status: Status
    completedCells: List[CompletedCell]
    completedCount: Optional[conint(ge=0, le=9)] = Field(None, examples=[6])
    pointsEarned: int = Field(..., examples=[120])
    completedAt: Optional[AwareDatetime] = Field(
        None, description='Set when all 9 cells are completed'
    )
    joinedAt: Optional[AwareDatetime] = None


class Photo(BaseModel):
    id: int
    familyId: int
    challengeId: Optional[int] = None
    activityIndex: Optional[conint(ge=0, le=8)] = None
    url: Optional[AnyUrl] = None
    uploadedAt: AwareDatetime


class Family1(BaseModel):
    id: Optional[int] = None
    displayName: Optional[str] = Field(None, examples=['Sarah & Emma'])
    profileImage: Optional[AnyUrl] = None


class Challenge1(BaseModel):
    id: Optional[int] = None
    title: Optional[str] = Field(None, examples=['Cooking Challenge'])


class FeedEntry(BaseModel):
    id: int
    family: Family1
    challenge: Challenge1
    activity: str = Field(..., examples=['Bake cookies together'])
    photoUrl: AnyUrl
    pointsAwarded: int = Field(..., examples=[20])
    createdAt: AwareDatetime


class LeaderboardEntry(BaseModel):
    rank: int = Field(..., examples=[1])
    family: Family1
    points: int = Field(..., examples=[340])


class Participant(BaseModel):
    familyId: Optional[int] = None
    displayName: Optional[str] = None
    profileImage: Optional[AnyUrl] = None
    online: Optional[bool] = None


class MediaType(Enum):
    video = 'video'
    audio = 'audio'


class MessageCreate(BaseModel):
    senderFamilyId: int
    text: Optional[str] = Field(
        None, description='Text content (required if no media is attached)'
    )
    mediaType: Optional[MediaType] = Field(
        None, description='Type of media attachment (if any)'
    )
    mediaUrl: Optional[AnyUrl] = Field(None, description='URL of the media attachment')


class Message(BaseModel):
    id: int
    conversationId: int
    senderFamilyId: int
    senderDisplayName: Optional[str] = Field(None, examples=['Sarah & Emma'])
    text: Optional[str] = None
    mediaType: Optional[MediaType] = None
    mediaUrl: Optional[AnyUrl] = None
    createdAt: AwareDatetime


class SearchResults(BaseModel):
    users: Optional[List[User]] = None
    families: Optional[List[Family]] = None
    challenges: Optional[List[ChallengeSummary]] = None


class FamiliesFamilyIdMembersPostRequest(BaseModel):
    userId: int = Field(..., examples=[7])


class FamiliesFamilyIdStreakGetResponse(BaseModel):
    familyId: Optional[int] = None
    currentStreak: Optional[int] = Field(
        None,
        description='Consecutive days with at least one completed activity',
        examples=[5],
    )
    longestStreak: Optional[int] = Field(None, examples=[12])


class ClassroomsClassroomIdFamiliesPostRequest(BaseModel):
    familyId: int = Field(..., examples=[3])


class ClassroomsClassroomIdFeedTogglePutRequest(BaseModel):
    feedEnabled: bool


class Status1(Enum):
    ongoing = 'ongoing'
    completed = 'completed'
    all = 'all'


class FamiliesFamilyIdChallengesChallengeIdActivitiesActivityIndexPostResponse(
    BaseModel
):
    activityIndex: Optional[int] = None
    photoId: Optional[int] = None
    pointsAwarded: Optional[int] = Field(None, examples=[20])
    progress: Optional[ChallengeProgress] = None


class Type(Enum):
    user = 'user'
    family = 'family'
    challenge = 'challenge'
    all = 'all'


class Conversation(BaseModel):
    id: int
    participants: List[Participant]
    lastMessage: Optional[Message] = None
    unreadCount: Optional[int] = Field(None, examples=[3])
