# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-05-26T08:17:01+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class User(BaseModel):
    id: Optional[int] = Field(None, examples=[4])
    name: Optional[str] = Field(None, examples=['Max Mustermann'])
    role: Optional[str] = Field(
        None,
        description='role can be either parent, child or teacher/admin',
        examples=['parent'],
    )


class Users(RootModel[List[User]]):
    root: List[User] = Field(..., description='Array of user info')
