"""drop challenge dates add shared groups

Revision ID: 387fb2accfe3
Revises: ebf9c5ba4963
Create Date: 2026-07-03 07:49:56.854101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '387fb2accfe3'
down_revision: Union[str, None] = 'ebf9c5ba4963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_shared_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'group_id', name='uq_challenge_shared_group')
    )
    op.create_index(op.f('ix_challenge_shared_groups_challenge_id'), 'challenge_shared_groups', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_shared_groups_group_id'), 'challenge_shared_groups', ['group_id'], unique=False)
    op.drop_column('challenges', 'end_date')
    op.drop_column('challenges', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('challenges', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_challenge_shared_groups_group_id'), table_name='challenge_shared_groups')
    op.drop_index(op.f('ix_challenge_shared_groups_challenge_id'), table_name='challenge_shared_groups')
    op.drop_table('challenge_shared_groups')
    # ### end Alembic commands ###
