"""add challenges and completions tables

Revision ID: d1d1fba86cde
Revises: 083b99406853
Create Date: 2026-05-30 05:49:13.912261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd1d1fba86cde'
down_revision: Union[str, None] = '083b99406853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_by_family_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('display_mode', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenge_activities',
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('grid_position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_activities_challenge_id'), 'challenge_activities', ['challenge_id'], unique=False)
    op.create_table('completions',
    sa.Column('challenge_activity_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('completed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('photo_key', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('shared_to_feed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_activity_id'], ['challenge_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'challenge_activity_id', name='uq_completion')
    )
    op.create_index(op.f('ix_completions_challenge_activity_id'), 'completions', ['challenge_activity_id'], unique=False)
    op.create_index(op.f('ix_completions_family_id'), 'completions', ['family_id'], unique=False)
    op.drop_constraint(op.f('uq_users_google_sub'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=False)
    op.create_unique_constraint(op.f('uq_users_google_sub'), 'users', ['google_sub'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_completions_family_id'), table_name='completions')
    op.drop_index(op.f('ix_completions_challenge_activity_id'), table_name='completions')
    op.drop_table('completions')
    op.drop_index(op.f('ix_challenge_activities_challenge_id'), table_name='challenge_activities')
    op.drop_table('challenge_activities')
    op.drop_table('challenges')
    # ### end Alembic commands ###
