"""add progress fields to families

Revision ID: fd1957537579
Revises: e5f6a7b8c9d0
Create Date: 2026-06-28 11:25:51.151084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd1957537579'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('families', sa.Column('weekly_goal', sa.Integer(), nullable=False, server_default='2'))
    op.add_column('families', sa.Column('streak_weeks', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('families', sa.Column('last_streak_weeks', sa.Integer(), nullable=True))
    op.add_column('families', sa.Column('longest_streak_weeks', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('families', sa.Column('last_activity_iso_week', sa.String(length=10), nullable=True))
    op.add_column('families', sa.Column('last_frozen_iso_week', sa.String(length=10), nullable=True))
    # Remove server defaults after backfilling — columns are managed by the application going forward
    op.alter_column('families', 'weekly_goal', server_default=None)
    op.alter_column('families', 'streak_weeks', server_default=None)
    op.alter_column('families', 'longest_streak_weeks', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('families', 'last_frozen_iso_week')
    op.drop_column('families', 'last_activity_iso_week')
    op.drop_column('families', 'longest_streak_weeks')
    op.drop_column('families', 'last_streak_weeks')
    op.drop_column('families', 'streak_weeks')
    op.drop_column('families', 'weekly_goal')
    # ### end Alembic commands ###
