export { apiClient, registerAuthHandlers } from './client';
export { onboardingApi } from './onboarding';
export type { ConsentPayload, FamilyPayload, ChildPayload } from './onboarding';
export { groupsApi } from './groups';
export type { FeedEntry } from './groups';
export { activitiesApi } from './activities';
export type { ActivityItem, ActivityFilters } from './activities';
export { challengesApi } from './challenges';
export type { ChallengeSummary, ChallengeWithProgress, ChallengeActivitySlot, Completion, CreateChallengePayload } from './challenges';
export { completionsApi, photosApi } from './completions';
export type { PhotoUrlResponse } from './completions';
